export const COVID_REQUEST = "COVID_REQUEST";
export const COVID_SUCCESS = "COVID_SUCCESS";
export const COVID_FAIL = "COVID_FAIL";



export const COVID_GET_REQUEST="COVID_GET_REQUEST"
export const COVID_GET_SUCCESS="COVID_GET_SUCCESS"
export const COVID_GET_ERROR="COVID_GET_ERROR"