export const RCAF_REQUEST = "RCAF_REQUEST";
export const RCAF_SUCCESS = "RCAF_SUCCESS";
export const RCAF_FAIL = "RCAF_FAIL";


export const RCAF_GET_REQUEST="RCAF_GET_REQUEST"
export const RCAF_GET_SUCCESS="RCAF_GET_SUCCESS"
export const RCAF_GET_ERROR="RCAF_GET_ERROR"